services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    volumes:
      - ./:/var/www/html
      - ./frontend/js:/var/www/html/js  # Mapeando a pasta frontend/js para /var/www/html/js
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script-OportunIF.sql:/docker-entrypoint-initdb.d/script-OportunIF.sql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
