services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script-OportunIF.sql:/docker-entrypoint-initdb.d/script-OportunIF.sql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
