services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3307:3306" # A porta do contêiner MySQL está exposta na porta 3307 do host
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
