
services:
  php-apache:
    image: php:8.2-apache
    container_name: php_apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
